### ISSUE TITLE
Routes Not Working

### ISSUE THREAD

**Issue by designcise** [HawkBitPhp/hawkbit#35]
Nothing besides the ```/``` root route gets captured. For example:

```
$app->get('/hello/{name}', function ($request, $response, $args) {
    $response->getBody()->write(
        sprintf('<h1>Hello, %s!</h1>', $args['name'])
    );
    return $response;
});
```

doesn't work! Neither does anything else besides ```/```. Could it be because of @BlackScorp 's PR?

**Comment by designcise** [comment]
This issue is resolved by removing ```RewriteBase /``` (as provided in the docs) from ```.htaccess```; maybe the docs need to be updated?

**Comment by mbunge** [comment]
Hello,

I need also to check if this happens on nginx. I guess rebase depends on the environment and where your index is called (root folder, subfolder).

**Comment by mbunge** [comment]
Fixed
