### ISSUE TITLE
HomeControlller Not Found

### ISSUE THREAD

**Issue by memran** [HawkBitPhp/hawkbit#40]
I have put the HomeController.php on src folder and thrown a error Whoops\Exception\ErrorException: Class 'HomeController' not found in file.

Where i should put this  file ?

my index.php like this:
`<?php
require __DIR__.'/../vendor/autoload.php';

$config = [
    'key' => '1234'
];

$app = new Hawkbit\Application($config);

$app->get('/', 'HomeController::index'); // calls index method on HomeController class

$app->run();
`

**Comment by BlackScorp** [comment]
if your HomeController has a namespace, you have to add it as well

$app->get('/', '\\My\\Fancy\\Namespace\\HomeController::index'); (double backslash) github formatter removed it

**Comment by mbunge** [comment]
Keep in mind to configure your namespace for src folder for psr-4 autoloading in composer.json too! 

https://getcomposer.org/doc/04-schema.md#psr-4

**Comment by memran** [comment]
solved by PSR-4 fixed on composer.json

**Comment by mbunge** [comment]
Ok super!

I close this issue ;)
